INSERT INTO book (title, author, isbn, stock) VALUES ('Akuntansi Pengantar 1', 'Supardi', '978-979-107-882-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Aplikasi Klinis Induk Ovulasi & Stimulasi Ovariu', 'Samsulhadi', '978-979-328-876-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Aplikasi Praktis Asuhan Keperawatan Keluarga', 'Komang Ayu Heni', '978-602-867-404-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('A-Z Psikologi : Berbagai kumpulan topik Psikologi', 'Zainul Anwar', '978-979-293-215-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Bangsa gagal ; Mencari identitas kebangsaan', 'Nasruddin Anshoriy', '978-979-128-365-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Biografi Gus Dur ; The Authorized Biography of KH. Abdurrahman Wahid (Soft Cover)', 'Greg Barton', '978-979-338-125-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Buku Ajar Tumbuh Kembang Remaja & Permasalahanya', 'Soetjiningsih', '979-328-808-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Cedera Kepala', 'M. Z. Arifin', '978-602-867-497-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Dasar Dasar Uroginekologi', 'Pribakti B', '978-602-867-451-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Etnografi Pengobatan; Praktik Budaya peramuan & sugesti komunitas adat Tau Taa Vana', 'Alie Humaedi', '978-602-728-136-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Hantu Digoel; Politik Pengamanan Politik Zaman Kolonial', 'Takashi Shiraishi', '979-896-678-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam Agama ramah perempuan; Pembelaan kiai pesantren', 'Husein Muhammad', '979-338-171-X', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam Jawa; Kesalehan Normatif Versus Kebatinan', 'Mark R. Woodward', '979-896-636-8', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam Pasar Keadilan; Artikulasi Lokal, Kapitalisme, dan Demokrasi', 'Robert W. Hefner', '979-896-679-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam Sasak ; Wetu telu versus waktu lima', 'Erni Budiwanti', '979-896-651-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Keanekaragaman klinik peny. Trofoblas gestasional', 'Djamhoer M', '978-602-867-468-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kesadaran Nasional ; dari kolonialisme sampai kemerdekaan (jilid 1)', 'Slamet Muljana', '978-979-128-355-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kesadaran Nasional ; dari kolonialisme sampai kemerdekaan (jilid 2)', 'Slamet Muljana', '978-979-128-357-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kesehjateraan Sosial', 'Isbandi Rukminto Adi', '978-979-769-600-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kolaborasi PHP 5 dan Mysql untuk pengembangan website + cd', 'Eko Priyo Utomo', '978-979-294-344-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kontroversi Hakim Perempuan Pada Peradilan Islam di Negara Negara Muslim', 'Djamizah Muqoddas', '978-979-255-344-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kuasa Wanita Jawa', 'Christina S Handayani', '979-338-159-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kumpulan Undang undang Sistem peradilan Pidana', 'Lincon Arsyad', '979-290-349-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Langsung Praktik Komputerisasi Akuntansi Dengan MYOB', 'Wahana Komputer', '978-979-295-172-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Lembaga keuangan Islam', 'Nurul Huda', '978-602-873-012-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Makna Budaya Dalam Komunikasi Antar Budaya', 'Alo Liliweri', '978-979-128-303-8', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Manajemen Penerbitan Jurnal Ilmiah', 'Lukman S', '978-602-867-471-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Menuju Puncak Kemegahan; Sejarah kerajaan Majapahit', 'Slamet Muljana', '979-845-135-X', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Metode Riset Bisnis Edisi II', 'Suliyanto', '978-979-290-742-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Metodologi Penelitian Bidang Kesehatan ED. 2', 'Moch. Imron TA', '978-602-271-037-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Neo Patriotisme; Etika kekuasaan dalam kebdayaan jawa', 'Nasruddin Anshoriy', '978-979-128-367-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('NU vis a vis Negara; Pencarian isi, bentuk dan makna', 'Andree Feillard', '979-896-633-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Otoritarianisme Hukum Islam ; Kritik atas hirearki teks al-kutub as-sittah', 'Muhammad Habibi Siregar', '978-602-149-135-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Otoritas Sunnah Non-Tasyri’iyyah menurut Yusuf Al-Qaradhawi', 'Tarmizi M. Jakfar', '978-979-254-840-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Panduan Penatalaksanaan Kanker Solid Peraboi 2010', 'Tjakra Wibawa', '978-602-867-417-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Patologi I (umum)', 'Sudarto Pringgoutomo', '979-328-803-5', '1');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengantar Cultural Studies : Sejarah, Pendekatan, Konseptual, & Isu Menuju Studi Budaya Kapitalisme lanjut', 'Sandi Suwardi Hasan', '978-979-254-856-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengantar Studi Al-Quran : Teori dan Pendekatan', 'Munzir Hitami', '978-979-255-380-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Politik Media dan Pertarungan Wacana', 'Agus Sudibyo', '979-949-233-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Quick Reference Windows 8', 'Wahana Komputer', '978-979-293-499-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Rekam Jejak; Dokter pejuang & Pelopor kebangkitan Nasional', 'Nasruddin Anshoriy', '978-979-128-361-8', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Runtuhnya Kerajaan Hindu Jawa', 'Slamet Muljana', '979-845-116-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Sejarah Pendidikan Nasional : Dari masa klasik hingga modern', 'Muhammad Rifa’i', '978-979-254-823-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Serangan Umum 1 Maret 1949 dalam keleidoskop Sejarah Perjuangan Mempertahankan Kemerdekaan Indonesia', 'Batara R. Hutagalung', '978-979-128-394-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Statistik Sosial; Teori dan aplikasi Program SPSS', 'Nanang Martono', '978-979-107-893-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Step by Step Penanganan Kelainan Endokrinologi', 'Tono Djuwantono', '978-602-867-485-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Strategi Bahasa Assembler + CD', 'Jason P', '979-346-964-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Strategic Management', 'Sofjan Assauri', '978-979-769-632-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Studi Filsafat 1 : Pembacaan atas tradisi islam kontemporer', 'Hassan Hanafi', '978-602-080-901-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Tan Malaka: Merajut Masyarakat dan pendidikan Indonesia yang Sosialistis', 'Syaifudin', '978-979-254-991-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Tarekat Petani : Fenomena Tarekat Syattariyah Lokal', 'Nur Syam', '978-979-167-765-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Tata Boga Industri : Materi Kompetensi Untuk SMK, LPK Pariwisata, & LPK Kapal Pesiar yang siap kerja', 'Bartono', '978-979-291-640-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Teks Otoritas Kebenaran', 'Nasr Hamid Abu Zaid', '979-255-359-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Teologi Seksual', 'Geoffrey Parrinder', '979-338-106-x', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Belajar mikrokontroler AT89C51/52/55', 'Agfianto EP', '979-346-916-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Shortcourse RPG Maker VX ACE', 'Wahana Komputer', '978-979-294-694-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Transnasionalisasi Masyarakat Sipil', 'Andi Widjajanto', '979-255-247-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Tuntunan Praktis : Pengembangan Aplikasi Sistem Informasi Geografis berbasis Dekstop dan Web + CD', 'Riyanto', '978-979-107-870-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Web Programing Membangun Aplikasi Web Handal dengan J2EE dan MVC', 'Widodo Budiharto', '978-979-294-131-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Ajeg Bali : Gerakan, Identitas Kultural, dan Globalisasi', 'Prof. Dr. Nengah Bawa Atmadja, MA', '978-979-128-398-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Aplikasi Program Akutansi dengan Visual FoxPro 9.0 Aplikasi Penjualan, Pembelian dan Stok', 'Peter Wanto', '978-979-107-853-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Aura dan Rinupa, Berdialog dengan Kayu, Bambu dan Batu.', 'Christina Johanes, Kristina, Maxy, Priyo', '978-979-294-169-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Buku Acuan Nasional Onkologi Ginekologi', 'Farid – Farid', '979-815-023-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Buku Ajar Gastroenterologi-Hipatology Thn 2016', 'M.Juffrie – M.Juffrie', '978-979-842-146-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Buku Pintar Pengelolaan BPR dan Lembaga Keuangan Pembiayaan Mikro', 'Ali SuyantoHerli', '978-979-293-544-8', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Busines And Personal Development', 'Josua Taringan dan Swenjiadi Yenawan', '978-979-294-016-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Cara pemeriksaan, Penyetelan dan Perawatan Kelistrikan Mobil', 'Boentarto', '979-533-956-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('DAFTAR TAJUK SUBYEK DALAM BAHASA INDONESIA', 'SULISTYO-BASUKI', '979-442-350-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('DESAIN PEMBELAJARAN BERBASIS PENDIDIKAN KARAKTER', 'Asmaun Sahlan & Angga Teguh Prastyo', '978-602-187-851-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Dunia Lebih Indah Tanpa Sekolah', 'Nanang Martono', '978-602-135-310-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Fiqh Ekonomi Syariah (Fiqh Muamalah)', 'DR. Mardani', '978-602-873-097-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Himpunan Undang-Undang Hak Kekayaan Intelektual', 'Massudilawe & Partner', '978-979-290-403-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Hukum Agraria Kajian Komprehensif', 'Dr. Urip Santoso, S.H., M.H', '978-602-873-098-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Ilmu Dakwah', 'Dr. Moh. Ali Aziz, M.AG', '978-979-346-559-X', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('IMS (IP Multimedia Subsystem), Framework Dan Arsitektur Jaringan Telekomunikasi Masa Depan', 'M. Azwir', '978-979-292-342-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam dan Permasalahan Sosial', 'Dr. A. Qodri A Azizy', '979-896-682-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Islam Pesisir', 'Dr. Nur Syam', '978-979-845-114-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Kupas Tuntas : Microsoft Windows 8.1', 'Madcoms', '978-979-294-506-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Langkah Mudah Belajar Kalkulus For IT(Khusus P. Jawa)', 'Sudaryono, Untung Rahardja, Edi S. Mulyanta', '978-979-291-769-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Manajemen Penanganan Barang-Barang Berbahaya Pada Angkatan Udara', 'Wynd Riyaldi & M Rifni', '978-602-752-348-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('MATA AIR PERADABAN ; Dua Milenium Wonosobo', 'H.A. Kholiq Arif', '978-979-225-331-4', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Membuat Aplikasi Sistem Aplikasi Menggunakan VB.NET', 'Yulius Ekaq Agung Saputro', '978-602-752-391-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Memuja Mantra ; Sabuk Mangir dan Jaran Goyang Masyarakat Suku Using Banyuwangi', 'Heru S.P. Saputra', '978-979-128-322-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Mendesain Model Pembelajaran Inovatif Progresif dan Kontekstual', 'Trianto, M.Pd', '978-602-118-605-3', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Menulis Itu Mudah ; Panduan Praktis Menjadi Penulis Handal', 'Sukino', '978-979-255-321-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Penelitian Kualitatif', 'Burhan Bungin', '978-979-392-588-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Mistisisme Hindu Muslim', 'R.C Zaehner', '979-338-134-5', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Nietzsche', 'St. Sunardi', '978-979-845-160-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Panduan Aplikasi dan Solusi: Pemodelan Obyek Dengan 3ds Max 2014', 'Wahana Komputer', '978-979-295-094-6', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Panduan Praktis Sistem Kendali Digital', 'Azwardi Dan Cekmas Cekdin', '978-979-295-109-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pantun Melayu : Titik Temu Islam dan Budaya Lokal Nusantara', 'Abd. Rachman Abror', '978-979-128-392-2', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pemrograman Web Membuat Sistem Informasi Akademik Sekolah Dengan PHP-MYSQL & Dreamweaver', 'Bunafit Nugroho', '978-602-786-966-0', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('PENDIDIKAN PASCAKONFLIK ; Pendidikan Multikultural Berbasis Konseling Budaya Masyarakat Maluku Utara', 'Dr. M. Tahir Sapsuha', '978-979-167-767-7', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengantar Membuat Robot', 'M. Ibnu Malik', '978-979-346-982-X', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengantar Teknologi Informasi', 'Tata Sutabri', '978-979-294-249-1', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengenalan Dasar-Dasar PLC (Progamable Logic Controler) Disertai Contoh Aplikasinya', 'M. Budiyanto', '979-970-886-9', '2');
INSERT INTO book (title, author, isbn, stock) VALUES ('Pengolahan Citra Digital : Konsep dan Teori', 'Fajar Astuti Hermawati', '978-979–293-119-8', '2');
