services:
  library-backend:
    build: .
    container_name: library-backend
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - APP_NAME=LIBARY_BACKEND
      - APP_ENV=DEVELOPMENT
      - APP_PORT=3000
      - DB_HOST=db-library
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234567890
      - DB_NAME=library
    networks:
      - libary-network
    depends_on:
      - db-library

  db-library:
    image: postgres
    container_name: db-library
    ports:
      - 5433:5432
    volumes:
      - ./db-library:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: library
    networks:
      - libary-network

networks:
  libary-network:
