package main

import (
	"log"
	"os"

	_ "github.com/FRFebi/library-backend/cmd/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/FRFebi/library-backend/delivery/http"
	"github.com/FRFebi/library-backend/infrastructure"
	"github.com/FRFebi/library-backend/repository"
	"github.com/FRFebi/library-backend/usecase"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	fiberSwagger "github.com/swaggo/fiber-swagger" // http://localhost:3000/swagger/index.html
)

//	@title			Library Backend API Documentation
//	@version		1.0
//	@description	This is Library Backend API documentation

//	@contact.name	Fiko Redha
//	@contact.email	fiko469@gmail.com

//	@host		localhost:3000
//	@BasePath	/

func main() {
	port := os.Getenv("APP_PORT")
	if port == "" {
		port = "3000"
	}

	app := fiber.New()
	app.Use(cors.New())
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	api := app.Group("/api")

	db := infrastructure.NewPostgreeDB()

	// Dependency Injection
	//1. Book
	bookRepo := repository.NewBookRepository(db)
	bookUC := usecase.NewBookUsecase(bookRepo)
	http.NewBookHandler(api, bookUC)

	//2. Borrower
	borrowerRepo := repository.NewBorrowerRepository(db)
	borrowerUC := usecase.NewBorrowerUsecase(borrowerRepo)
	http.NewBorrowerHandler(api, borrowerUC)

	//3. Loan
	loanRepo := repository.NewLoanRepository(db)
	loanUC := usecase.NewLoanUsecase(loanRepo, bookRepo)
	http.NewLoanHandler(api, loanUC)

	log.Fatal(app.Listen(":" + port))

}
